/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as IndexImport } from './routes/index'
import { Route as ActivitiesNewImport } from './routes/activities.new'
import { Route as ActivitiesActivityIdImport } from './routes/activities.$activityId'
import { Route as ActivitiesActivityIdEditImport } from './routes/activities.$activityId_.edit'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActivitiesNewRoute = ActivitiesNewImport.update({
  id: '/activities/new',
  path: '/activities/new',
  getParentRoute: () => rootRoute,
} as any)

const ActivitiesActivityIdRoute = ActivitiesActivityIdImport.update({
  id: '/activities/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRoute,
} as any)

const ActivitiesActivityIdEditRoute = ActivitiesActivityIdEditImport.update({
  id: '/activities/$activityId_/edit',
  path: '/activities/$activityId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdImport
      parentRoute: typeof rootRoute
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/activities/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewImport
      parentRoute: typeof rootRoute
    }
    '/activities/$activityId_/edit': {
      id: '/activities/$activityId_/edit'
      path: '/activities/$activityId/edit'
      fullPath: '/activities/$activityId/edit'
      preLoaderRoute: typeof ActivitiesActivityIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users': typeof UsersRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/users': typeof UsersRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/activities/$activityId_/edit': typeof ActivitiesActivityIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/activities/$activityId'
    | '/activities/new'
    | '/activities/$activityId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users'
    | '/activities/$activityId'
    | '/activities/new'
    | '/activities/$activityId/edit'
  id:
    | '__root__'
    | '/'
    | '/users'
    | '/activities/$activityId'
    | '/activities/new'
    | '/activities/$activityId_/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRoute: typeof UsersRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  ActivitiesNewRoute: typeof ActivitiesNewRoute
  ActivitiesActivityIdEditRoute: typeof ActivitiesActivityIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  ActivitiesNewRoute: ActivitiesNewRoute,
  ActivitiesActivityIdEditRoute: ActivitiesActivityIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users",
        "/activities/$activityId",
        "/activities/new",
        "/activities/$activityId_/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/activities/$activityId": {
      "filePath": "activities.$activityId.tsx"
    },
    "/activities/new": {
      "filePath": "activities.new.tsx"
    },
    "/activities/$activityId_/edit": {
      "filePath": "activities.$activityId_.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
